# Generated by Django 2.0.1 on 2018-01-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FilePathField(allow_files=False, allow_folders=True)),
                ('access_mode', models.CharField(choices=[('R', 'Read'), ('W', 'Write'), ('RW', 'Read-Write')], default='R', max_length=2)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
