# Generated by Django 2.0.1 on 2018-01-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20180130_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/', recursive=True),
        ),
    ]
