# Generated by Django 2.0.1 on 2018-01-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20180130_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='show_hidden_files',
            field=models.BooleanField(default=False),
        ),
    ]
