# Generated by Django 2.0.1 on 2018-01-31 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_location_show_hidden_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='path',
        ),
    ]
